global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'local-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:8080' ] # EC2 배포시 해당 IP로 변경
        labels:
          env: 'local'
          app: 'order-service'
