spring:
  application:
    name: Lucky-Burger
  jpa:
    properties:
      hibernate:
        format_sql: false
    show_sql: true
  flyway:
    enabled: false
    baseline-on-migrate: false
    baseline-version: 0
    locations:
      - classpath:db/migration

server:
  port: 8080
  tomcat:
    max-connections: 2000
    accept-count: 1000
    threads:
      max: 128

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.core.env: DEBUG
    org.springframework.boot.context.config: DEBUG
    com.zaxxer.hikari: DEBUG