spring:
  config:
    import:
      - "aws-parameterstore:/config/dev/"
  datasource:
    url: jdbc:mysql://${db.host}:${db.port:3306}/${db.name}?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: ${db.username}
    password: ${db.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: false
        generate_statistics: true
        dialect: org.hibernate.dialect.MySQLDialect

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:redis}
      port: ${SPRING_DATA_REDIS_PORT:6379}

management:
  endpoints:
    web:
      exposure:
        include: [ "*" ]
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
      region: my-region
      uri: true
      status: true
      command: true
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
        redis:
          commands:
            command: true
        jdbc:
          connections:
            acquire: true


jwt:
  secret:
    aesKey: ${jwt.aes_key}
    key: ${jwt.secret_key}
    whiteList:
      - /api/v1/signup
      - /api/v1/login
      - /api/v1/menus/**
      - /api/v1/coupons/**
      - /api/v1/shops/**
      - /api/v1/events/**
      - /actuator/health
      - /actuator/prometheus
      - /swagger-ui/**
      - /v3/api-docs/**
      - /swagger-resources/**

  token:
    prefix: 'Bearer '
    expiration: ${jwt.expiration}
