spring:
  application:
    name: Lucky-Burger
  profiles:
    active: local
  flyway:
    enabled: false
    baseline-on-migrate: false
    baseline-version: 0
    locations:
      - classpath:db/migration

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: false
        generate_statistics: true
  datasource:
    hikari:
      pool-name: hikari-pool

server:
  port: 8080
  tomcat:
    max-connections: 2000
    accept-count: 1000
    threads:
      max: 128

management:
  endpoints:
    web:
      exposure:
        include: [ "*" ]
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
      region: my-region
      uri: true
      status: true
      command: true
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
        redis:
          commands:
            command: true
        jdbc:
          connections:
            acquire: true


logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.core.env: DEBUG
    org.springframework.boot.context.config: DEBUG
    com.zaxxer.hikari: DEBUG