spring:
  application:
    name: Lucky-Burger
  profiles:
    active: local
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: false
        generate_statistics: true
  datasource:
    hikari:
      pool-name: hikari-pool
  flyway:
    enabled: true
    # 이력 테이블 이름
    table: flyway_schema_history
    # 기존 비어있지 않은 스키마를 기준선으로 등록
    baseline-on-migrate: false   # 최초 한번 구동 후에는 false로 변경
    # baseline-version: 0   # 최초 한번 구동 후에는 미사용

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: [ "*" ]
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
      region: my-region
      uri: true
      status: true
      command: true
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
        redis:
          commands:
            command: true
        jdbc:
          connections:
            acquire: true


logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.core.env: DEBUG
    org.springframework.boot.context.config: DEBUG
    com.zaxxer.hikari: DEBUG