spring:
  config:
    import: optional:file:.env.local[.properties]
  datasource:
    url: jdbc:mysql://localhost:3306/luckyburger?serverTimezone=Asia/Seoul
    username: root
    password: "000620"
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 21
      leak-detection-threshold: 3000
  jpa:
    hibernate:
      ddl-auto: update
  autoconfigure:
    exclude:
      - io.awspring.cloud.autoconfigure.config.parameterstore.ParameterStoreAutoConfiguration
  data:
    redis:
      host: localhost
      port: 6379

  cache:
    type: redis


jwt:
  secret:
    aesKey: MDEyMzQ1Njc4OWFiY2RlZg==
    key: bXlTdXBlclNlY3JldEtleTEyMzQ1Njc4OTBhYmNkZWYhQCM
    whiteList:
      - /api/v1/signup
      - /api/v1/login
      - /api/v1/menus/**
      - /api/v1/coupons/**
      - /api/v1/owner/**
      - /api/v1/events/**
      - /actuator/health
      - /actuator/prometheus
      - /api/v1/admin

  token:
    prefix: 'Bearer '
    expiration: 3600000
