spring:
  config:
    import: optional:file:.env.local[.properties]
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

jwt:
  secret:
    aesKey: ${AES_KEY}
    key: ${JWT_KEY}
    whiteList:
      - /api/v1/signup
      - /api/v1/login
      - /api/v1/menus/**
      - /api/v1/coupons/**
      - /api/v1/shops/**
      - /api/v1/events/**
      - /api/v1/actuator/health
      - /actuator/prometheus

  token:
    prefix: 'Bearer '
    expiration: ${JWT_EXPIRATION}
